# Config for grunt-docma
# https://github.com/onury/grunt-docma
# https://github.com/onury/docma
{
    # Default options
    options: {
        # Task specific options
        traceFatal: true,           # (0|false)|(1|true)|2
        # Docma specific config
        # See all @ https://github.com/onury/docma
        config: {
            jsdoc: {
                encoding: 'utf8',
                recurse: false,
                pedantic: false,
                access: null, # ['private'],
                package: null,
                module: true,
                undocumented: false,
                undescribed: false,
                hierarchy: true,
                sort: 'grouped',
                # 'relativePath': '../code',
                filter: null
            },
            debug: 0
        }
    },
    code: {
        # target specific options
        options: {
            # Docma config
            config: {
                template: {
                    path: 'default',
                    document: {
                        title: 'Code Docs'
                    },
                    options: {}
                }
            }
        },
        # files to be processed
        src: [
            './test/code/**/*.js'
        ],
        dest: './test/doc-code'
    },
    other: {
        # target specific options
        options: {
            # Docma config
            config: {
                template: {
                    options: {
                        badges: false
                    }
                }
            }
        },
        # files to be processed
        src: [
            './test/code/src/lib/*.js'
        ],
        dest: './test/doc-other'
    },
    fromFile: {
        # target specific options
        options: {
            # Docma config file (src and dest defined in file)
            config: './test/docma.config.json'
        }
    },
    fromFile2: {
        # target specific options
        options: {
            # Docma config file
            config: './test/docma.config.json'
        },
        # files to be processed (overwrites src and dest defined in config file)
        src: [
            './test/code/src/lib/*.js'
        ],
        dest: './test/doc-from-file-2'
    },
}
